#!/bin/bash

REPOHOST=https://github.com

if [ $# -lt 1 ]; then
    echo "Usage: $0 COMMAND [options]"
    echo ""
    echo "Run COMMAND against each component"
    echo ""
    echo "Special commands: archive, packlite, sincerelease"
    exit
fi

PRINT_NAME=0
if [ $1 == "-s" ]; then
    # assume caller is script
    # do not print extraneous names
    PRINT_NAME=1
    shift
fi

COMPONENTS="kvtree   \
           axl      \
           spath    \
           shuffile \
           redset   \
           er       \
           rankstr  \
           lwgrp    \
           dtcmp    \
           scr"

ORGS="ecp-veloc/kvtree   \
     ecp-veloc/axl      \
     ecp-veloc/spath    \
     ecp-veloc/shuffile \
     ecp-veloc/redset   \
     ecp-veloc/er       \
     ecp-veloc/rankstr  \
     hpc/lwgrp          \
     hpc/dtcmp          \
     llnl/scr"

if [ $1 == "clone" ]; then
    for i in $ORGS; do
        if [ $PRINT_NAME ]; then
            echo -e "\n$i:"
        fi
        git clone $REPOHOST/$i
    done
    exit
fi

ARCH_DIR="scr-archive"
mkdir -p $ARCH_DIR

if [ $1 == "archive" ]; then
    for i in $COMPONENTS; do
        cd $i
	TAG=`git describe --tags $(git rev-list --tags --max-count=1)`
        if [ $PRINT_NAME ]; then
            echo "Archiving $i version $TAG"
        fi
        git archive --format=tar --prefix=$i/ $TAG | gzip > $i-$TAG.tar.gz 2> /dev/null
        cd ..

        cd $ARCH_DIR
        tar -zxf ../$i/$i-$TAG.tar.gz
        cd ..
    done

    # last TAG is from SCR
    # last in COMPONENTS variable
    mv $ARCH_DIR scr-top-$TAG
    cp CMakeLists.txt NOTICE scr-top-$TAG
    tar -czf scr-top-$TAG.tgz scr-top-$TAG
    rm -rf scr-top-$TAG
    echo -e "\n Created: scr-top-$TAG.tgz\nunpack with tar -xzf scr-top-$TAG.tgz"
    exit
fi

## WARING: copy-paste of archive loop above
if [ $1 == "packlite" ]; then
    for i in $COMPONENTS; do
        cd $i
        if [ $PRINT_NAME ]; then
            echo "Packing up $i"
        fi
        git archive --format=tar --prefix=$i/ HEAD | gzip > $i-lite.tar.gz
	cd ..

        cd $ARCH_DIR
        tar -zxf ../$i/$i-lite.tar.gz
        cd ..
    done

    mv $ARCH_DIR scr-top-packlite
    cp CMakeLists.txt NOTICE scr-top-packlite
    tar -czf scr-top-packlite.tgz scr-top-packlite
    rm -rf scr-top-packlite
    echo -e "\n Created: scr-top-packlite.tgz\nunpack with tar -xzf scr-top-packlite.tgz"
    exit
fi

if [ $1 == "sincerelease" ]; then
    for i in $COMPONENTS; do
        cd $i
        echo "$i"
        echo -n "  Release: "
        git describe --tags --abbrev=0
        echo -n "  Commits: "
        git rev-list $(git describe --tags --abbrev=0)..HEAD --count
        cd ..
    done
    exit
fi

## NON-speical commands
## Run command against all repos
for i in $COMPONENTS; do
    if [ $PRINT_NAME ]; then
        echo -e "\n$i:"
    fi
    cd $i
    git $@
    cd ..
done
