name: build-and-test

# Inspired by mfem
# https://github.com/mfem/mfem/blob/master/.github/workflows/builds-and-tests.yml

permissions:
  actions: write

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        target: [Debug, Release]
        # CMAKE_BUILD_TYPE values go here
        #
        mpi: [par]
        # additional option: seq
        #
        #
        # 'include' allows us to:
        # - Add a variable to all jobs without creating a new matrix dimension.
        #   Codecov is defined that way.
        include:
          - target: Debug
            codecov: NO
          - target: Release
            codecov: YES
          - os: ubuntu-latest
            target: Release
            codecov: NO
            mpi: par
          - os: ubuntu-latest
            target: Release
            codecov: NO
            mpi: par
    name: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.mpi }}

    runs-on: ${{ matrix.os }}

    steps:

    - name: checkout scr-top
      uses: actions/checkout@v2
      with:
        path: scr-top
        fetch-depth: 0

    - name: get deps scr-top
      uses: ecp-veloc/github-actions/get-scr-os-deps@main
      with:
        os: ${{ matrix.os }}
        mpi: ${{ matrix.mpi }}


    # Only get MPI if defined for the job.
    # TODO: It would be nice to have only one step, e.g. with a dedicated
    # action, but I (@adrienbernede) don't see how at the moment.

    - name: build all
      run: |
        cd scr-top
        make clone
        make build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=${{ matrix.target }}
        make

    - name: test kvtree
      run: |
        cd scr-top/build/kvtree-prefix/src/kvtree-build/
        make check

    - name: test rankstr
      run: |
        cd scr-top/build/rankstr-prefix/src/rankstr-build/
        make check

    - name: test redset
      run: |
        cd scr-top/build/redset-prefix/src/redset-build/
        make check

    - name: test shuffile
      run: |
        cd scr-top/build/shuffile-prefix/src/shuffile-build/
        make check

    - name: test er
      run: |
        cd scr-top/build/er-prefix/src/er-build/
        make check

    - name: test axl
      run: |
        cd scr-top/build/axl-prefix/src/axl-build/
        make check

    - name: test spath
      run: |
        cd scr-top/build/spath-prefix/src/spath-build/
        make check

    - name: test scr
      run: |
        cd scr-top/build/scr-prefix/src/scr-build/
        make check
